name = "16type"
compatibility_date = "2024-11-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]

